export const TENURE_TYPES = [
  { code: "ASY", value: "Asylum Seeker" },
  { code: "COM", value: "Commercial Let" },
  { code: "FRE", value: "Freehold" },
  { code: "FRS", value: "Freehold (Serv)" },
  { code: "INT", value: "Introductory" },
  { code: "LEA", value: "Leasehold (RTB)" },
  { code: "LTA", value: "License Temp Ac" },
  { code: "LHS", value: "Lse 100%" },
  { code: "MPA", value: "Mense Profit Ac" },
  { code: "NON", value: "Non-Secure" },
  { code: "PVG", value: "Private Garage" },
  { code: "SPS", value: "Private Sale LH" },
  { code: "RSL", value: "Registered Social Landlord" },
  { code: "RTM", value: "Rent to Mortgage" },
  { code: "SEC", value: "Secure" },
  { code: "SSE", value: "Shared Equity" },
  { code: "SHO", value: "Shared Owners" },
  { code: "SLL", value: "Short Life Lse" },
  { code: "TLA", value: "Temp Annex" },
  { code: "TBB", value: "Temp B&B" },
  { code: "DEC", value: "Temp Decant" },
  { code: "THO", value: "Temp Hostel" },
  { code: "THL", value: "Temp Hostel Lse" },
  { code: "TPL", value: "Temp Private Lt" },
  { code: "TRA", value: "Temp Traveller" },
  { code: "TAF", value: "Tenant Acc Flat" },
  { code: "TGA", value: "Tenant Garage" },
];
